# mint run xcodegen generate

name: FitScope
options:
  bundleIdPrefix: com.akitorahayashi
  createIntermediateGroups: true
  defaultConfig: Debug
  
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  IPHONEOS_DEPLOYMENT_TARGET: 15.0
  SWIFT_VERSION: 5.0

configs:
  Debug: debug
  Release: release

targets:
  FitScope:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - FitScope
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.fitscope
      INFOPLIST_FILE: FitScope/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_ASSET_PATHS: FitScope/Resources

  FitScopeTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - FitScopeTests
    dependencies:
      - target: FitScope
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.fitscope.tests
      INFOPLIST_FILE: FitScopeTests/Info.plist

  FitScopeUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - FitScopeUITests
    dependencies:
      - target: FitScope
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.fitscope.uitests
      INFOPLIST_FILE: FitScopeUITests/Info.plist

schemes:
  FitScope:
    build:
      targets:
        FitScope: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - FitScopeTests
        - FitScopeUITests
    archive:
      config: Release

  FitScopeTests:
    build:
      targets:
        FitScopeTests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - FitScopeTests

  FitScopeUITests:
    build:
      targets:
        FitScopeUITests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - FitScopeUITests

